#!/usr/bin/env python

import sys
import os
import shutil

def stripCVS (dir):
	for filename in os.listdir(dir):
		path = os.path.join (dir, filename)
		if filename == "CVS":
			shutil.rmtree (path)
		elif os.path.isdir (path):
			stripCVS (path)

if __name__ == "__main__":

	path = os.getcwd()
	if len (sys.argv) > 1:
		path = os.path.join (path, sys.argv[1])
	print "stripCVS: %s" % path
	if not os.path.isdir (path):
		print "\nstripCVS required a DIRECTORY"
	else:
		stripCVS (path)

