#!/usr/bin/env python

import sys
import os
import shutil

def stripSVN (dir):
	for filename in os.listdir(dir):
		path = os.path.join (dir, filename)
		if filename == ".svn":
			shutil.rmtree (path)
		elif os.path.isdir (path):
			stripSVN (path)

if __name__ == "__main__":

	path = os.getcwd()
	if len (sys.argv) > 1:
		path = os.path.join (path, sys.argv[1])
	print "stripSVN: %s" % path
	if not os.path.isdir (path):
		print "\nstripSVN required a DIRECTORY"
	else:
		stripSVN (path)

