#!/usr/bin/env python

import sys, os, site
import string

if (sys.platform == 'win32'):
	sys.path.append ("H:\\python-lib")
else:
	sys.path.append ("/home/ostwald/python-lib")


from urlparse import urlsplit, urljoin
from dcsTools import ExportCollectionClient

if __name__ == "__main__":
	usage = """
dcs-export usage:
   1 - command (\'dcs-export\')
   2 - dcs instance (e.g., 'http://dcs.dlese.org/news/services/dcsws1-0')
   3 - collection to export (e.g., 'news')
"""
	# showArgs()
	if len (sys.argv) != 3:
		print usage
		sys.exit()

	baseUrl = sys.argv[1]
	collection = sys.argv[2]

	params = {'verb':'ExportCollection','collection': collection}
	client = ExportCollectionClient (baseUrl)
	client.doExport (params)

					   

		

	
