#!/usr/bin/env python

import sys

## sys.path.append ("H:\\python-lib")

import os
from dcsTools.dcs_data import BatchUpdater

if __name__ == "__main__":

	cwd = os.getcwd()
	if len (sys.argv) > 1:
		cwd = os.path.join (cwd, sys.argv[1])
	# print "prefixer: %s" % cwd
	print "\n --- DCS DATA UPDATER (to version 1.0 ---"
	dirName = os.path.split(cwd)[1]
	if not os.path.isdir (cwd) or dirName != "dcs_data":
		print "\nprefixer required a dcs_data directory (curent directory is %s)" % dirName
		sys.exit()

	print "calling DcsDataRecord updater ..."
	BatchUpdater (cwd)
	
