#!/usr/bin/env python

import sys
import os
import utils
from statusMaker import StatusMaker
import time

def showArgs ():
	for i in range(len (sys.argv)):
		print "\t arg[%d]: %s" % (i, sys.argv[i])

if __name__ == "__main__":
	env = utils.getTransEnv ()
# 	env.printenv()
	sm = StatusMaker (env)
	tics = time.time()
	sm.run()
	elapsed = time.time() - tics
	print "%d records written in %.1f seconds (%.1f recs/sec)" % \
		  (sm.records_written, elapsed, sm.records_written / elapsed)
	print "sanity check:"
	print "\t there are %d records in %s" % (utils.countfiles (sm.records),
											 sm.records)
	print "\t there are %d records in %s" % (utils.countfiles (sm.dcs_status),
											 sm.dcs_status)
	
