#!/usr/bin/env python

import sys
import os
import utils
from statusCounter import StatusCounter

if __name__ == "__main__":

	path = os.getcwd()
	if len (sys.argv) > 1:
		path = os.path.abspath (sys.argv[1])
	print "counting all .xml files under %s ..." %  path
	sc = StatusCounter (path)
	sc.processDir()
	sc.report()
